import profileImg from "../assets/profile_icon.png";

export const customers = [
  {
    id: 1,
    image: profileImg,
    name: 'ephraim ephraim' ,
    email: 'ephraim@gmail.com' ,
    orders: 453,
    spend: '$56746',
    joined: new Date().toLocaleDateString(),
    location: 'Ghana',
  },
  {
    id: 2,
    image: profileImg,
    name: 'ephraim ephraim' ,
    email: 'ephraim@gmail.com' ,
    orders: 453,
    spend: '$56746',
    joined: new Date().toLocaleDateString(),
    location: 'Ghana',
  },
  {
    id: 3,
    image: profileImg,
    name: 'ephraim ephraim' ,
    email: 'ephraim@gmail.com' ,
    orders: 453,
    spend: '$56746',
    joined: new Date().toLocaleDateString(),
    location: 'Ghana',
  },
  {
    id: 4,
    image: profileImg,
    name: 'ephraim ephraim' ,
    email: 'ephraim@gmail.com' ,
    orders: 453,
    spend: '$56746',
    joined: new Date().toLocaleDateString(),
    location: 'Ghana',
  },
  {
    id: 5,
    image: profileImg,
    name: 'ephraim ephraim' ,
    email: 'ephraim@gmail.com' ,
    orders: 453,
    spend: '$56746',
    joined: new Date().toLocaleDateString(),
    location: 'Ghana',
  },
  {
    id: 6,
    image: profileImg,
    name: 'ephraim ephraim' ,
    email: 'ephraim@gmail.com' ,
    orders: 453,
    spend: '$56746',
    joined: new Date().toLocaleDateString(),
    location: 'Ghana',
  },
  {
    id: 7,
    image: profileImg,
    name: 'ephraim ephraim' ,
    email: 'ephraim@gmail.com' ,
    orders: 453,
    spend: '$56746',
    joined: new Date().toLocaleDateString(),
    location: 'Ghana',
  },
  {
    id: 8,
    image: profileImg,
    name: 'ephraim ephraim' ,
    email: 'ephraim@gmail.com' ,
    orders: 453,
    spend: '$56746',
    joined: new Date().toLocaleDateString(),
    location: 'Ghana',
  },
]